### ISSUE TITLE
weird failures on OF Travis

### ISSUE THREAD

**Issue by bilderbuchi** [HalfdanJ/ofDocGenerator#3]
Hey @HalfdanJ ,
I am encountering weird error when trying to run the docs build on the OF travis, see [this line](https://travis-ci.org/openframeworks/openFrameworks/jobs/72072631#L1893) and following. Any idea what is going wrong there?

Also, interestingly, `npm run start` does not error out when encountering an error (i.e. the exit code is still 0 because a subsequent command seems to run without error) - that is what made me only realize now that the builds were failing. Any idea why this is or how to correct it?

**Comment by HalfdanJ** [comment]
Some doxygen parsing error. Should be fixed with (haven't tested) https://github.com/HalfdanJ/ofDocGenerator/commit/e9d3bbbb8de243f4957b62123ce9f7c9340aa33d

**Comment by bilderbuchi** [comment]
Nice, we shall see [soon](https://travis-ci.org/openframeworks/openFrameworks/jobs/72186112), that build is currently in the queue.

Also, is there an easy way you can make `npm run start` return non-zero exit if stuff goes wrong? Right now the builds fail, but Travis still shows green, see e.g. [on the bottom of this page](https://travis-ci.org/openframeworks/openFrameworks/jobs/72184814).

**Comment by bilderbuchi** [comment]
third, while I have you on the horn, is the libreoffice dependency really necessary? It's quite the big package I'm pulling in with every CI build, I left it out for now...
edit: ah I see it, that's just the key/repo... even more confusing?

**Comment by bilderbuchi** [comment]
Now the error is `TypeError: Cannot read property 'length' of null` at `if(matches.length >= 2){` - I am guessing that the regex match fails, producing an empty/null object `matches`, which then doesn't have a length... see [here](https://travis-ci.org/openframeworks/openFrameworks/jobs/72186112#L1642)

**Comment by bilderbuchi** [comment]
> Also, is there an easy way you can make npm run start return non-zero exit if stuff goes wrong?

I am not too familiar with your code, but I think in  [this line](https://github.com/HalfdanJ/ofDocGenerator/blob/2832ef79a4c3deb2198e19cbc24e6f19e37bd607/package.json#L12), the script entry should be `npm run doxygen && npm run parse && npm run sass` so that it only runs all the commands if the preceding ones succeed - this would (correctly) bail if one step fails.
Do you agree, and would you change that?

**Comment by HalfdanJ** [comment]
Okay hmm.. I don't have time currently to look into it. For now, just disable my part of the travis script.

**Comment by bilderbuchi** [comment]
OK, w.r.t. the bail-on-error, see PR #4.

I also worked around the TypeError above (by checking if matches!=null) - this does not crash, but at the same time [skips processing the XML](https://travis-ci.org/openframeworks/openFrameworks/jobs/72263687#L1636-L1642) - for some reason it finds no matches at all, but I can't find where your travis test differs significantly from the travis integration in OF, or what could cause this?

**Comment by bilderbuchi** [comment]
the only differences I can find is some [truncated output](https://travis-ci.org/openframeworks/openFrameworks/jobs/72270319#L318) during npm install (you have `underscore@1.8.3 node_modules/underscore`), and node v0.10.36 instead of 0.10.40.
